spring:
  application:
    name: employees
  datasource:
    initialization-mode: always
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-ui
server:
  port: {PORT:8080}
